#ifndef VELOCITY_SERVO_TAG_INTERFACES__VISIBILITY_CONTROL_H_
#define VELOCITY_SERVO_TAG_INTERFACES__VISIBILITY_CONTROL_H_
#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define VELOCITY_SERVO_TAG_INTERFACES_EXPORT __attribute__ ((dllexport))
    #define VELOCITY_SERVO_TAG_INTERFACES_IMPORT __attribute__ ((dllimport))
  #else
    #define VELOCITY_SERVO_TAG_INTERFACES_EXPORT __declspec(dllexport)
    #define VELOCITY_SERVO_TAG_INTERFACES_IMPORT __declspec(dllimport)
  #endif
  #ifdef VELOCITY_SERVO_TAG_INTERFACES_BUILDING_LIBRARY
    #define VELOCITY_SERVO_TAG_INTERFACES_PUBLIC VELOCITY_SERVO_TAG_INTERFACES_EXPORT
  #else
    #define VELOCITY_SERVO_TAG_INTERFACES_PUBLIC VELOCITY_SERVO_TAG_INTERFACES_IMPORT
  #endif
  #define VELOCITY_SERVO_TAG_INTERFACES_PUBLIC_TYPE VELOCITY_SERVO_TAG_INTERFACES_PUBLIC
  #define VELOCITY_SERVO_TAG_INTERFACES_LOCAL
#else
  #define VELOCITY_SERVO_TAG_INTERFACES_EXPORT __attribute__ ((visibility("default")))
  #define VELOCITY_SERVO_TAG_INTERFACES_IMPORT
  #if __GNUC__ >= 4
    #define VELOCITY_SERVO_TAG_INTERFACES_PUBLIC __attribute__ ((visibility("default")))
    #define VELOCITY_SERVO_TAG_INTERFACES_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define VELOCITY_SERVO_TAG_INTERFACES_PUBLIC
    #define VELOCITY_SERVO_TAG_INTERFACES_LOCAL
  #endif
  #define VELOCITY_SERVO_TAG_INTERFACES_PUBLIC_TYPE
#endif
#endif  // VELOCITY_SERVO_TAG_INTERFACES__VISIBILITY_CONTROL_H_
// Generated 26-Jul-2026 22:25:23
 