%% plot_fr3_joint_limit_test.m
% FR3关节位置、命令速度、命令加速度综合测试脚本
%
% 自动读取：
%   log_joint_position          7维关节位置，rad
%   log_command_velocity        7维最终命令速度，rad/s
%   log_command_acceleration    7维命令加速度，rad/s^2
%
% 输出3个Figure：
%   1. 关节位置 + URDF硬限位 + 中央60%回中边界
%   2. 关节命令速度 + 速度限幅
%   3. 关节命令加速度 + 加速度限幅
%
% 自动保存：
%   PNG、FIG和3份CSV指标文件
%
% 使用：
%   完成一次Simulink测试后运行：
%
%       plot_fr3_joint_limit_test
%
% 说明：
%   - 自动忽略收到第一条合法JointState之前的默认零值。
%   - 使用print优先保存PNG，避免Linux下exportgraphics偶发报错。

%% =========================================================
%% 1. 用户可调参数
%% =========================================================

% 与Mapper一致：中央60%范围内不启动回中。
centerFreeRatio = 0.80;

% 与velocity_command_node一致：
% 最终速度上限 = FR3官方速度上限 * maxVelocityScale
maxVelocityScale = 0.40;

% 与velocity_command_node一致，单位rad/s^2。
maxJointAccelerations = [ ...
    0.50;
    0.50;
    0.50;
    0.50;
    0.50;
    0.50;
    0.50];

% 图片保存参数。
imageResolutionDpi = 200;
closeFiguresAfterSave = false;

% 输出目录。
outputFolder = fullfile( ...
    pwd, ...
    'test_results', ...
    'joint_command_monitor');

%% =========================================================
%% 2. FR3官方限制
%% =========================================================

% FR3官方关节速度上限，单位rad/s。
fr3MaxJointVelocitiesOfficial = [ ...
    2.62;
    2.62;
    2.62;
    2.62;
    5.26;
    4.18;
    5.26];

% FR3关节位置硬限位，来自fr3.urdf，单位rad。
qMin = [ ...
    -2.9007;
    -1.8361;
    -2.9007;
    -3.0770;
    -2.8763;
     0.4398;
    -3.0508];

qMax = [ ...
     2.9007;
     1.8361;
     2.9007;
    -0.1169;
     2.8763;
     4.6216;
     3.0508];

%% =========================================================
%% 3. 派生限制
%% =========================================================

qMid = 0.5*(qMin + qMax);
qHalfRange = 0.5*(qMax - qMin);

qCenterLower = ...
    qMid - centerFreeRatio*qHalfRange;

qCenterUpper = ...
    qMid + centerFreeRatio*qHalfRange;

commandVelocityLimit = ...
    fr3MaxJointVelocitiesOfficial*maxVelocityScale;

commandAccelerationLimit = ...
    maxJointAccelerations(:);

%% =========================================================
%% 4. 读取3类日志
%% =========================================================

jointSignal = findLoggedSignal( ...
    'log_joint_position');

velocitySignal = findLoggedSignal( ...
    'log_command_velocity');

accelerationSignal = findLoggedSignal( ...
    'log_command_acceleration');

if isempty(jointSignal)
    error([ ...
        '没有找到log_joint_position。' ...
        '请确认模型已记录7维关节位置。']);
end

if isempty(velocitySignal)
    error([ ...
        '没有找到log_command_velocity。' ...
        '请确认模型已记录7维最终命令速度。']);
end

if isempty(accelerationSignal)
    error([ ...
        '没有找到log_command_acceleration。' ...
        '请确认模型已记录7维命令加速度。']);
end

[timeQ,qData] = ...
    signalToTimeData(jointSignal);

[timeV,vData] = ...
    signalToTimeData(velocitySignal);

[timeA,aData] = ...
    signalToTimeData(accelerationSignal);

validateSevenJointData( ...
    qData, ...
    'log_joint_position');

validateSevenJointData( ...
    vData, ...
    'log_command_velocity');

validateSevenJointData( ...
    aData, ...
    'log_command_acceleration');

%% =========================================================
%% 5. 删除JointState启动阶段默认零值
%% =========================================================

% 第一条有效关节状态必须满足7个关节均位于URDF硬限位内。
insideAllJointLimits = all( ...
    qData >= qMin.' & ...
    qData <= qMax.', ...
    2);

firstValidJointIndex = find( ...
    insideAllJointLimits, ...
    1, ...
    'first');

if isempty(firstValidJointIndex)
    error( ...
        '整段日志中没有找到合法的7维关节位置。');
end

if firstValidJointIndex > 1
    fprintf( ...
        ['忽略JointState启动阶段的%d个无效采样点，' ...
         '原始时间约为%.3f s。\n'], ...
        firstValidJointIndex-1, ...
        timeQ(firstValidJointIndex));
end

qData = qData(firstValidJointIndex:end,:);
timeQ = timeQ(firstValidJointIndex:end);
timeQ = timeQ - timeQ(1);

%% =========================================================
%% 6. 清理NaN和Inf
%% =========================================================

[timeQ,qData] = removeNonfiniteRows( ...
    timeQ, ...
    qData, ...
    'joint position');

[timeV,vData] = removeNonfiniteRows( ...
    timeV, ...
    vData, ...
    'command velocity');

[timeA,aData] = removeNonfiniteRows( ...
    timeA, ...
    aData, ...
    'command acceleration');

%% =========================================================
%% 7. 关节位置指标
%% =========================================================

lowerMargin = qData - qMin.';
upperMargin = qMax.' - qData;

nearestMargin = min( ...
    lowerMargin, ...
    upperMargin);

% 0%=关节中点，100%=硬限位。
normalizedPosition = ...
    (qData - qMid.') ./ qHalfRange.';

limitUsagePercent = ...
    100*abs(normalizedPosition);

minimumMargin = min( ...
    nearestMargin, ...
    [], ...
    1, ...
    'omitnan');

maximumUsagePercent = max( ...
    limitUsagePercent, ...
    [], ...
    1, ...
    'omitnan');

finalPosition = qData(end,:);

%% =========================================================
%% 8. 命令速度指标
%% =========================================================

velocityUsagePercent = ...
    100*abs(vData) ./ commandVelocityLimit.';

maximumVelocityUsagePercent = max( ...
    velocityUsagePercent, ...
    [], ...
    1, ...
    'omitnan');

maximumVelocityAbs = max( ...
    abs(vData), ...
    [], ...
    1, ...
    'omitnan');

finalVelocity = vData(end,:);

%% =========================================================
%% 9. 命令加速度指标
%% =========================================================

accelerationUsagePercent = ...
    100*abs(aData) ./ commandAccelerationLimit.';

maximumAccelerationUsagePercent = max( ...
    accelerationUsagePercent, ...
    [], ...
    1, ...
    'omitnan');

maximumAccelerationAbs = max( ...
    abs(aData), ...
    [], ...
    1, ...
    'omitnan');

finalAcceleration = aData(end,:);

%% =========================================================
%% 10. 输出目录
%% =========================================================

if ~exist(outputFolder,'dir')
    mkdir(outputFolder);
end

timeStamp = char( ...
    datetime( ...
        'now', ...
        'Format','yyyyMMdd_HHmmss'));

fileBase = fullfile( ...
    outputFolder, ...
    ['fr3_joint_command_monitor_',timeStamp]);

%% =========================================================
%% 11. Figure 1：7关节位置
%% =========================================================

fig1 = figure( ...
    'Name','FR3 Joint Position Monitor', ...
    'NumberTitle','off', ...
    'Color','w', ...
    'Position',[80 60 1500 900]);

layout1 = tiledlayout( ...
    fig1, ...
    4, ...
    2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

title( ...
    layout1, ...
    'FR3 Joint Positions, Hard Limits and 60% Center-Free Region');

for jointIndex = 1:7
    ax = nexttile(layout1,jointIndex);

    plot( ...
        ax, ...
        timeQ, ...
        qData(:,jointIndex), ...
        'LineWidth',1.25);

    hold(ax,'on');

    yline( ...
        ax, ...
        qMin(jointIndex), ...
        'r--', ...
        'Lower hard limit', ...
        'LabelHorizontalAlignment','left');

    yline( ...
        ax, ...
        qMax(jointIndex), ...
        'r--', ...
        'Upper hard limit', ...
        'LabelHorizontalAlignment','left');

    yline( ...
        ax, ...
        qCenterLower(jointIndex), ...
        'k:', ...
        '60% lower boundary', ...
        'LabelHorizontalAlignment','left');

    yline( ...
        ax, ...
        qCenterUpper(jointIndex), ...
        'k:', ...
        '60% upper boundary', ...
        'LabelHorizontalAlignment','left');

    yline( ...
        ax, ...
        qMid(jointIndex), ...
        'b-.', ...
        'Center', ...
        'LabelHorizontalAlignment','left');

    grid(ax,'on');
    xlabel(ax,'Time (s)');
    ylabel(ax,sprintf('q_%d (rad)',jointIndex));

    positionPadding = ...
        0.08*(qMax(jointIndex)-qMin(jointIndex));

    ylim( ...
        ax, ...
        [ ...
            qMin(jointIndex)-positionPadding, ...
            qMax(jointIndex)+positionPadding ...
        ]);

    if maximumUsagePercent(jointIndex) >= 100
        titleColor = [0.85 0.10 0.10];
        stateText = 'HARD LIMIT EXCEEDED';

    elseif maximumUsagePercent(jointIndex) >= ...
            100*centerFreeRatio
        titleColor = [0.85 0.45 0.05];
        stateText = 'CENTERING ACTIVE';

    else
        titleColor = [0.10 0.50 0.10];
        stateText = 'CENTER REGION';
    end

    title( ...
        ax, ...
        sprintf( ...
            ['Joint %d | %s | min margin %.4f rad | ' ...
             'max usage %.1f%%'], ...
            jointIndex, ...
            stateText, ...
            minimumMargin(jointIndex), ...
            maximumUsagePercent(jointIndex)), ...
        'Color',titleColor);

    if jointIndex == 1
        legend( ...
            ax, ...
            { ...
                'q', ...
                'Lower hard limit', ...
                'Upper hard limit', ...
                '60% lower', ...
                '60% upper', ...
                'Center' ...
            }, ...
            'Location','best');
    end
end

axSummary1 = nexttile(layout1,8);
axis(axSummary1,'off');

summaryLines1 = strings(9,1);
summaryLines1(1) = "Joint position summary";
summaryLines1(2) = "---------------------------------------------";

for jointIndex = 1:7
    summaryLines1(jointIndex+2) = sprintf( ...
        ['J%d: final=% .4f rad | min margin=%.4f rad | ' ...
         'max usage=%.1f%%'], ...
        jointIndex, ...
        finalPosition(jointIndex), ...
        minimumMargin(jointIndex), ...
        maximumUsagePercent(jointIndex));
end

text( ...
    axSummary1, ...
    0.02, ...
    0.98, ...
    summaryLines1, ...
    'Units','normalized', ...
    'VerticalAlignment','top', ...
    'FontName','Consolas', ...
    'FontSize',10);

drawnow;

saveFigureSafely( ...
    fig1, ...
    [fileBase,'_joint_position'], ...
    imageResolutionDpi);

%% =========================================================
%% 12. Figure 2：7关节命令速度
%% =========================================================

fig2 = figure( ...
    'Name','FR3 Command Velocity Monitor', ...
    'NumberTitle','off', ...
    'Color','w', ...
    'Position',[100 80 1500 900]);

layout2 = tiledlayout( ...
    fig2, ...
    4, ...
    2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

title( ...
    layout2, ...
    sprintf( ...
        ['FR3 Command Velocity | ' ...
         'Applied Limit = Official Limit x %.2f'], ...
        maxVelocityScale), ...
    'Interpreter','none');

for jointIndex = 1:7
    ax = nexttile(layout2,jointIndex);

    plot( ...
        ax, ...
        timeV, ...
        vData(:,jointIndex), ...
        'LineWidth',1.25);

    hold(ax,'on');

    yline( ...
        ax, ...
        commandVelocityLimit(jointIndex), ...
        'r--', ...
        'Upper velocity limit', ...
        'LabelHorizontalAlignment','left');

    yline( ...
        ax, ...
        -commandVelocityLimit(jointIndex), ...
        'r--', ...
        'Lower velocity limit', ...
        'LabelHorizontalAlignment','left');

    yline(ax,0,'k:');

    grid(ax,'on');
    xlabel(ax,'Time (s)');
    ylabel(ax,sprintf('dq_%d (rad/s)',jointIndex));

    plottedPeak = max( ...
        maximumVelocityAbs(jointIndex), ...
        commandVelocityLimit(jointIndex));

    plotPadding = max( ...
        0.05, ...
        0.15*plottedPeak);

    ylim( ...
        ax, ...
        [ ...
            -plottedPeak-plotPadding, ...
             plottedPeak+plotPadding ...
        ]);

    if maximumVelocityUsagePercent(jointIndex) > 100
        titleColor = [0.85 0.10 0.10];
        stateText = 'VELOCITY LIMIT EXCEEDED';
    else
        titleColor = [0.10 0.50 0.10];
        stateText = 'WITHIN LIMIT';
    end

    title( ...
        ax, ...
        sprintf( ...
            ['Joint %d | %s | peak |dq| %.4f rad/s | ' ...
             'max usage %.1f%%'], ...
            jointIndex, ...
            stateText, ...
            maximumVelocityAbs(jointIndex), ...
            maximumVelocityUsagePercent(jointIndex)), ...
        'Color',titleColor);

    if jointIndex == 1
        legend( ...
            ax, ...
            { ...
                'dq command', ...
                'Upper limit', ...
                'Lower limit', ...
                'Zero' ...
            }, ...
            'Location','best');
    end
end

axSummary2 = nexttile(layout2,8);
axis(axSummary2,'off');

summaryLines2 = strings(10,1);
summaryLines2(1) = "Command velocity summary";
summaryLines2(2) = "---------------------------------------------";
summaryLines2(3) = sprintf( ...
    "maxVelocityScale = %.3f", ...
    maxVelocityScale);

for jointIndex = 1:7
    summaryLines2(jointIndex+3) = sprintf( ...
        ['J%d: limit=%.4f | final=% .4f rad/s | ' ...
         'peak=%.4f | usage=%.1f%%'], ...
        jointIndex, ...
        commandVelocityLimit(jointIndex), ...
        finalVelocity(jointIndex), ...
        maximumVelocityAbs(jointIndex), ...
        maximumVelocityUsagePercent(jointIndex));
end

text( ...
    axSummary2, ...
    0.02, ...
    0.98, ...
    summaryLines2, ...
    'Units','normalized', ...
    'VerticalAlignment','top', ...
    'FontName','Consolas', ...
    'FontSize',10);

drawnow;

saveFigureSafely( ...
    fig2, ...
    [fileBase,'_command_velocity'], ...
    imageResolutionDpi);

%% =========================================================
%% 13. Figure 3：7关节命令加速度
%% =========================================================

fig3 = figure( ...
    'Name','FR3 Command Acceleration Monitor', ...
    'NumberTitle','off', ...
    'Color','w', ...
    'Position',[120 100 1500 900]);

layout3 = tiledlayout( ...
    fig3, ...
    4, ...
    2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

title( ...
    layout3, ...
    ['FR3 Command Acceleration and ' ...
     'Per-Joint Acceleration Limits']);

for jointIndex = 1:7
    ax = nexttile(layout3,jointIndex);

    plot( ...
        ax, ...
        timeA, ...
        aData(:,jointIndex), ...
        'LineWidth',1.25);

    hold(ax,'on');

    yline( ...
        ax, ...
        commandAccelerationLimit(jointIndex), ...
        'r--', ...
        'Upper acceleration limit', ...
        'LabelHorizontalAlignment','left');

    yline( ...
        ax, ...
        -commandAccelerationLimit(jointIndex), ...
        'r--', ...
        'Lower acceleration limit', ...
        'LabelHorizontalAlignment','left');

    yline(ax,0,'k:');

    grid(ax,'on');
    xlabel(ax,'Time (s)');
    ylabel(ax,sprintf('ddq_%d (rad/s^2)',jointIndex));

    plottedPeak = max( ...
        maximumAccelerationAbs(jointIndex), ...
        commandAccelerationLimit(jointIndex));

    plotPadding = max( ...
        0.05, ...
        0.15*plottedPeak);

    ylim( ...
        ax, ...
        [ ...
            -plottedPeak-plotPadding, ...
             plottedPeak+plotPadding ...
        ]);

    if maximumAccelerationUsagePercent(jointIndex) > 100
        titleColor = [0.85 0.10 0.10];
        stateText = 'ACCEL LIMIT EXCEEDED';
    else
        titleColor = [0.10 0.50 0.10];
        stateText = 'WITHIN LIMIT';
    end

    title( ...
        ax, ...
        sprintf( ...
            ['Joint %d | %s | peak |ddq| %.4f rad/s^2 | ' ...
             'max usage %.1f%%'], ...
            jointIndex, ...
            stateText, ...
            maximumAccelerationAbs(jointIndex), ...
            maximumAccelerationUsagePercent(jointIndex)), ...
        'Color',titleColor);

    if jointIndex == 1
        legend( ...
            ax, ...
            { ...
                'ddq command', ...
                'Upper limit', ...
                'Lower limit', ...
                'Zero' ...
            }, ...
            'Location','best');
    end
end

axSummary3 = nexttile(layout3,8);
axis(axSummary3,'off');

summaryLines3 = strings(10,1);
summaryLines3(1) = "Command acceleration summary";
summaryLines3(2) = "---------------------------------------------";
summaryLines3(3) = "Per-joint acceleration limits (rad/s^2):";

for jointIndex = 1:7
    summaryLines3(jointIndex+3) = sprintf( ...
        ['J%d: limit=%.3f | final=% .4f rad/s^2 | ' ...
         'peak=%.4f | usage=%.1f%%'], ...
        jointIndex, ...
        commandAccelerationLimit(jointIndex), ...
        finalAcceleration(jointIndex), ...
        maximumAccelerationAbs(jointIndex), ...
        maximumAccelerationUsagePercent(jointIndex));
end

text( ...
    axSummary3, ...
    0.02, ...
    0.98, ...
    summaryLines3, ...
    'Units','normalized', ...
    'VerticalAlignment','top', ...
    'FontName','Consolas', ...
    'FontSize',10);

drawnow;

saveFigureSafely( ...
    fig3, ...
    [fileBase,'_command_acceleration'], ...
    imageResolutionDpi);

%% =========================================================
%% 14. 保存3份CSV指标
%% =========================================================

jointPositionMetrics = table( ...
    (1:7).', ...
    qMin, ...
    qMax, ...
    qCenterLower, ...
    qCenterUpper, ...
    finalPosition.', ...
    minimumMargin.', ...
    maximumUsagePercent.', ...
    'VariableNames',{ ...
        'Joint', ...
        'LowerLimitRad', ...
        'UpperLimitRad', ...
        'Center60LowerRad', ...
        'Center60UpperRad', ...
        'FinalPositionRad', ...
        'MinimumMarginRad', ...
        'MaximumLimitUsagePercent'});

commandVelocityMetrics = table( ...
    (1:7).', ...
    fr3MaxJointVelocitiesOfficial, ...
    repmat(maxVelocityScale,7,1), ...
    commandVelocityLimit, ...
    finalVelocity.', ...
    maximumVelocityAbs.', ...
    maximumVelocityUsagePercent.', ...
    'VariableNames',{ ...
        'Joint', ...
        'OfficialVelocityLimitRadPerSec', ...
        'VelocityScale', ...
        'AppliedVelocityLimitRadPerSec', ...
        'FinalVelocityRadPerSec', ...
        'PeakAbsVelocityRadPerSec', ...
        'MaximumVelocityUsagePercent'});

commandAccelerationMetrics = table( ...
    (1:7).', ...
    commandAccelerationLimit, ...
    finalAcceleration.', ...
    maximumAccelerationAbs.', ...
    maximumAccelerationUsagePercent.', ...
    'VariableNames',{ ...
        'Joint', ...
        'AccelerationLimitRadPerSec2', ...
        'FinalAccelerationRadPerSec2', ...
        'PeakAbsAccelerationRadPerSec2', ...
        'MaximumAccelerationUsagePercent'});

writetable( ...
    jointPositionMetrics, ...
    [fileBase,'_joint_position_metrics.csv']);

writetable( ...
    commandVelocityMetrics, ...
    [fileBase,'_command_velocity_metrics.csv']);

writetable( ...
    commandAccelerationMetrics, ...
    [fileBase,'_command_acceleration_metrics.csv']);

%% =========================================================
%% 15. 可选关闭图窗
%% =========================================================

if closeFiguresAfterSave
    closeValidFigure(fig1);
    closeValidFigure(fig2);
    closeValidFigure(fig3);
end

fprintf('\nFR3综合测试完成。\n');
fprintf('输出目录：\n%s\n\n',outputFolder);
fprintf('关节位置图：\n%s_joint_position.png\n',fileBase);
fprintf('命令速度图：\n%s_command_velocity.png\n',fileBase);
fprintf('命令加速度图：\n%s_command_acceleration.png\n\n',fileBase);

%% =========================================================
%% 局部函数
%% =========================================================

function signal = findLoggedSignal(signalName)

signal = [];
candidateOutputNames = {'out','simOut'};

for outputIndex = 1:numel(candidateOutputNames)
    outputName = candidateOutputNames{outputIndex};

    existsInBase = evalin( ...
        'base', ...
        sprintf( ...
            'exist(''%s'',''var'')', ...
            outputName));

    if ~existsInBase
        continue;
    end

    simulationOutput = evalin( ...
        'base', ...
        outputName);

    if ~isa( ...
            simulationOutput, ...
            'Simulink.SimulationOutput')
        continue;
    end

    outputNames = simulationOutput.who;

    if any(strcmp(outputNames,signalName))
        signal = simulationOutput.get(signalName);
        return;
    end

    if any(strcmp(outputNames,'logsout'))
        logsout = simulationOutput.get('logsout');

        if isa( ...
                logsout, ...
                'Simulink.SimulationData.Dataset')
            try
                element = logsout.getElement(signalName);
                signal = element.Values;
                return;
            catch
            end
        end
    end
end

existsDirectly = evalin( ...
    'base', ...
    sprintf( ...
        'exist(''%s'',''var'')', ...
        signalName));

if existsDirectly
    signal = evalin( ...
        'base', ...
        signalName);
end

end

function [time,data] = signalToTimeData(signal)

if isa( ...
        signal, ...
        'Simulink.SimulationData.Signal')
    signal = signal.Values;
end

if isa(signal,'timeseries')
    time = double(signal.Time(:));
    data = signal.Data;

elseif isstruct(signal) && ...
        isfield(signal,'time') && ...
        isfield(signal,'signals')
    time = double(signal.time(:));
    data = signal.signals.values;

elseif istimetable(signal)
    time = seconds( ...
        signal.Properties.RowTimes ...
        - signal.Properties.RowTimes(1));

    time = double(time(:));
    data = signal.Variables;

else
    error( ...
        '不支持的日志格式：%s', ...
        class(signal));
end

data = squeeze(data);

if isvector(data)
    data = data(:);

elseif size(data,1) == 7 && ...
        size(data,2) == numel(time)
    data = data.';

elseif size(data,1) ~= numel(time) && ...
        size(data,2) == numel(time)
    data = data.';

elseif size(data,1) ~= numel(time)
    data = reshape( ...
        data, ...
        numel(time), ...
        []);
end

data = double(data);

end

function validateSevenJointData(data,signalName)

if size(data,2) ~= 7
    error( ...
        '%s必须包含7列，当前尺寸为%s。', ...
        signalName, ...
        mat2str(size(data)));
end

end

function [time,data] = removeNonfiniteRows( ...
    time, ...
    data, ...
    signalDescription)

validRows = ...
    isfinite(time) & ...
    all(isfinite(data),2);

removedCount = sum(~validRows);

if removedCount > 0
    fprintf( ...
        '从%s中删除%d个NaN或Inf采样点。\n', ...
        signalDescription, ...
        removedCount);
end

time = time(validRows);
data = data(validRows,:);

if isempty(time)
    error( ...
        '%s清理后没有有效数据。', ...
        signalDescription);
end

end

function saveFigureSafely( ...
    figureHandle, ...
    fileBase, ...
    resolutionDpi)

if ~isgraphics(figureHandle,'figure')
    error( ...
        '准备保存%s时图窗句柄已经无效。', ...
        fileBase);
end

drawnow;

pngPath = [fileBase,'.png'];
figPath = [fileBase,'.fig'];

% Linux下优先使用print保存PNG。
try
    print( ...
        figureHandle, ...
        pngPath, ...
        '-dpng', ...
        sprintf('-r%d',resolutionDpi));

catch printError
    warning( ...
        ['print保存PNG失败，改用exportgraphics。\n' ...
         '原因：%s'], ...
        printError.message);

    if ~isgraphics(figureHandle,'figure')
        error( ...
            '回退保存时图窗已经无效：%s', ...
            fileBase);
    end

    exportgraphics( ...
        figureHandle, ...
        pngPath, ...
        'Resolution',resolutionDpi);
end

if isgraphics(figureHandle,'figure')
    savefig( ...
        figureHandle, ...
        figPath);
else
    warning( ...
        'PNG已保存，但FIG未保存，因为图窗已失效：%s', ...
        fileBase);
end

end

function closeValidFigure(figureHandle)

if isgraphics(figureHandle,'figure')
    close(figureHandle);
end

end