%% TEST_STAGE1_CONTROLLER_EQUIVALENCE
% 代码作用：
% 使用完全相同的cL、JL、rho、Kc和lambdaC，同时调用原模型控制器
% 与当前Core控制器，比较中心误差、条件指标和七维关节速度。
%
% 使用方法：
% 1. 先运行stereo_ibvs_config，使工作区存在cfg；
% 2. 将本脚本与两个控制器函数放在同一文件夹；
% 3. 将两个函数文件名分别改为：
%    original_stage1_controller.m
%    core_stage1_controller.m
% 4. 运行test_stage1_controller_equivalence。
%
% 通过条件：
% centerError最大差值 < 1e-12
% qDot最大差值        < 1e-9
% 条件指标最大差值    < 1e-12

%% 1. 检查配置和函数
if ~exist('cfg','var')
    error('Stage1Test:CfgMissing', ...
        '工作区中不存在cfg，请先运行stereo_ibvs_config。');
end

scriptDir = fileparts(mfilename('fullpath'));
addpath(scriptDir);

requiredFunctions = {
    'original_stage1_controller'
    'core_stage1_controller'
};

for functionIndex = 1:numel(requiredFunctions)
    if exist(requiredFunctions{functionIndex},'file') ~= 2
        error('Stage1Test:FunctionMissing', ...
            '找不到函数：%s.m',requiredFunctions{functionIndex});
    end
end

%% 2. Stage 1测试参数
% 原模型中与Stage 1无关的功能全部关闭：
% EKF前馈关闭、鲁棒项关闭、深度任务关闭、零空间任务关闭。
numericalEpsilon = 1e-12;
robustEnable = 0;
betaC = 0;
epsilonC = 1e-6;

betaRho = 0;
epsilonRho = 1e-6;
kRho = 0;
lambdaRho = 0.03;

nullspaceEnable = 0;
kNull = 0;
qMid = 0.5*(cfg.qMin + cfg.qMax);
leftOnlyCenterControlEnable = 1;

validLeft = 1;
cameraModelValid = 1;
kinematicsValid = 1;
controllerEnable = 1;

ekfPredictionValid = 0;
centerEnable = 1;
depthEnable = 0;
armEnable = 1;
depthTaskWeight = 0;

vHatLeft = zeros(3,1);
rhoHatL = cfg.rhoD;

%% 3. 测试图像坐标
% 分别覆盖右下、左下、右上、左上、图像中心和较小误差。
featureCases = [
     0.040,  0.020
    -0.040,  0.020
     0.040, -0.020
    -0.040, -0.020
     0.000,  0.000
     0.010, -0.008
].';

%% 4. 生成多组合法FR3关节角
rng(1);

numberOfJointCases = 20;
jointRange = cfg.qMax - cfg.qMin;

qLower = cfg.qMin + 0.15*jointRange;
qUpper = cfg.qMax - 0.15*jointRange;

qCases = zeros(7,numberOfJointCases);
qCases(:,1) = cfg.qInitial;

for jointCaseIndex = 2:numberOfJointCases
    qCases(:,jointCaseIndex) = ...
        qLower + rand(7,1).*(qUpper-qLower);
end

%% 5. 逐组比较
numberOfFeatureCases = size(featureCases,2);
numberOfTests = numberOfJointCases*numberOfFeatureCases;

centerErrorDifference = zeros(numberOfTests,1);
qDotDifference = zeros(numberOfTests,1);
qDotInternalDifference = zeros(numberOfTests,1);
conditionDifference = zeros(numberOfTests,1);
coreValid = zeros(numberOfTests,1);

testIndex = 0;

for jointCaseIndex = 1:numberOfJointCases
    q = qCases(:,jointCaseIndex);

    % MATLAB geometricJacobian原始顺序：
    % [角速度; 线速度]，并在机器人基座坐标系表达。
    JRaw = geometricJacobian( ...
        cfg.robot, ...
        q, ...
        cfg.cameraBodyName);

    T_CL2B = getTransform( ...
        cfg.robot, ...
        q, ...
        cfg.cameraBodyName, ...
        cfg.robotBaseName);

    R_CL2B = T_CL2B(1:3,1:3);
    R_B2CL = R_CL2B.';

    % 控制器要求的JL：
    % [线速度; 角速度]，并在左相机坐标系表达。
    JL = [
        R_B2CL*JRaw(4:6,:)
        R_B2CL*JRaw(1:3,:)
    ];

    for featureCaseIndex = 1:numberOfFeatureCases
        testIndex = testIndex + 1;
        cLMeasured = featureCases(:,featureCaseIndex);

        [ ...
            qDotOriginal, ...
            centerErrorOriginal, ...
            ~, ...
            conditionOriginal, ...
            ~, ...
            qDotCenterOriginal, ...
            ~, ...
            ~, ...
            ~ ...
        ] = original_stage1_controller( ...
            q, ...
            cLMeasured, ...
            rhoHatL, ...
            vHatLeft, ...
            JL, ...
            cfg.centerDesired, ...
            cfg.rhoD, ...
            validLeft, ...
            ekfPredictionValid, ...
            centerEnable, ...
            depthEnable, ...
            armEnable, ...
            depthTaskWeight, ...
            numericalEpsilon, ...
            robustEnable, ...
            betaC, ...
            epsilonC, ...
            cfg.Kc, ...
            cfg.lambdaC, ...
            betaRho, ...
            epsilonRho, ...
            kRho, ...
            lambdaRho, ...
            nullspaceEnable, ...
            kNull, ...
            qMid, ...
            leftOnlyCenterControlEnable);

        [ ...
            qDotCore, ...
            centerErrorCore, ...
            centerTaskValidCore, ...
            conditionCore ...
        ] = core_stage1_controller( ...
            cLMeasured, ...
            JL, ...
            validLeft, ...
            cameraModelValid, ...
            kinematicsValid, ...
            controllerEnable, ...
            cfg.centerDesired, ...
            cfg.rhoD, ...
            cfg.Kc, ...
            cfg.lambdaC);

        centerErrorDifference(testIndex) = ...
            max(abs(centerErrorOriginal-centerErrorCore));

        qDotDifference(testIndex) = ...
            max(abs(qDotOriginal-qDotCore));

        qDotInternalDifference(testIndex) = ...
            max(abs(qDotCenterOriginal-qDotCore));

        conditionDifference(testIndex) = ...
            abs(conditionOriginal-conditionCore);

        coreValid(testIndex) = centerTaskValidCore;
    end
end

%% 6. 输出结果
maxCenterErrorDifference = max(centerErrorDifference);
maxQDotDifference = max(qDotDifference);
maxQDotInternalDifference = max(qDotInternalDifference);
maxConditionDifference = max(conditionDifference);

fprintf('\n========== Stage 1控制器等价性测试 ==========\n');
fprintf('测试总数：%d\n',numberOfTests);
fprintf('centerError最大差值：       %.3e\n', ...
    maxCenterErrorDifference);
fprintf('qDotCmd最大差值：           %.3e\n', ...
    maxQDotDifference);
fprintf('qDotCenter最大差值：        %.3e\n', ...
    maxQDotInternalDifference);
fprintf('条件指标最大差值：          %.3e\n', ...
    maxConditionDifference);
fprintf('Core有效测试数：            %d / %d\n', ...
    sum(coreValid > 0.5),numberOfTests);

toleranceCenterError = 1e-12;
toleranceQDot = 1e-9;
toleranceCondition = 1e-12;

testPassed = ...
    maxCenterErrorDifference < toleranceCenterError && ...
    maxQDotDifference < toleranceQDot && ...
    maxQDotInternalDifference < toleranceQDot && ...
    maxConditionDifference < toleranceCondition && ...
    all(coreValid > 0.5);

if testPassed
    fprintf('\nPASS：两个Stage 1中心控制器数值等价。\n');
else
    fprintf('\nFAIL：两个控制器存在超过阈值的差异。\n');

    resultTable = table( ...
        centerErrorDifference, ...
        qDotDifference, ...
        qDotInternalDifference, ...
        conditionDifference, ...
        coreValid);

    resultTable = sortrows( ...
        resultTable, ...
        'qDotDifference', ...
        'descend');

    disp('差异最大的前10组：');
    disp(resultTable(1:min(10,height(resultTable)),:));

    error('Stage1Test:NotEquivalent', ...
        'Stage 1控制器等价性测试未通过。');
end
