function [v_camera_commanded,camera_command_valid] = ...
    command_to_camera_velocity(J_camera_base,command_velocity,T_camera2base, ...
    joint_count,joint_age,command_count,command_age, ...
    joint_state_timeout_sec,command_velocity_timeout_sec)
%COMMAND_TO_CAMERA_VELOCITY 将最终7关节命令速度换算为相机系XY线速度。
% 输出仅作为滤波器已知运动输入，不直接加入控制器输出。

v_camera_commanded=zeros(2,1); camera_command_valid=false;
command_velocity=reshape(command_velocity,7,1);
input_ok=joint_count>=7 && command_count>=7 && ...
    isfinite(joint_age) && joint_age<=joint_state_timeout_sec && ...
    isfinite(command_age) && command_age<=command_velocity_timeout_sec && ...
    isequal(size(J_camera_base),[6 7]) && ...
    isequal(size(T_camera2base),[4 4]) && ...
    all(isfinite(command_velocity)) && all(isfinite(J_camera_base(:))) && ...
    all(isfinite(T_camera2base(:)));
if ~input_ok, return; end

camera_twist_base=J_camera_base*command_velocity;
R_base_camera=T_camera2base(1:3,1:3);
v_camera_camera=R_base_camera'*camera_twist_base(4:6);
v_camera_commanded=v_camera_camera(1:2);
camera_command_valid=all(isfinite(v_camera_commanded));
if ~camera_command_valid, v_camera_commanded(:)=0; end
end

