function outputModelFile = build_single_camera_joint_velocity_direct(sourceModelFile)
%BUILD_SINGLE_CAMERA_JOINT_VELOCITY_DIRECT
% 以现有 single_camera_xy_tracking_isnew 模型为底稿，生成一个由
% Simulink 直接向 JointVelocityExampleController 发布 7 维关节速度的模型。
%
% 新控制链路：
%   原消息接收/校验与原四状态匀速 KF 使能逻辑
%       -> 完整点特征视觉雅可比 (2x7)
%       -> 阻尼冗余关节速度求解
%       -> 零空间关节中心、软限位和深度安全区任务
%       -> 最底层唯一一次关节速度低通、整体速度缩放和整体加速度限制
%       -> /joint_velocity_example_controller/commands
%
% 说明：
% 1. 不修改源模型，输出 single_camera_joint_velocity_direct.slx。
% 2. 不再使用 Python 速度映射/转发节点。
% 3. 原 KF 中的前馈低通、XY 速度限幅和 XY 加速度限幅参数已删除。
% 4. 原 safe_valid、target_visible、target_is_new、P/FF/controller_enable
%    使能关系保持不变；仅把其二维相机平移请求交给完整视觉雅可比求解。
% 5. JointState 按 name 重排为 fr3_joint1...fr3_joint7；名称缺失、重复或
%    position/velocity 对应索引不存在时，本次关节反馈判为无效。
% 6. 第一次只能在仿真或 dry-run 下检查方向、坐标系和 Topic，不能直接高速上机。
%
% 用法：
%   build_single_camera_joint_velocity_direct( ...
%       'single_camera_xy_tracking_isnew.slx');
%
% 如果不传文件名，脚本会在当前文件夹、upload 子文件夹和当前工作目录
% 中查找 single_camera_xy_tracking_isnew*.slx。

if nargin < 1 || isempty(sourceModelFile)
    sourceModelFile = findSourceModel();
end

sourceModelFile = char(sourceModelFile);
assert(isfile(sourceModelFile), ...
    '找不到源模型：%s', sourceModelFile);

buildFolder = fileparts(mfilename('fullpath'));
outputModel = 'single_camera_joint_velocity_direct';
outputModelFile = fullfile(buildFolder, [outputModel '.slx']);

% 上传后的文件名可能带“(1)”，不是合法 Simulink 模型名。
% 先复制到一个合法的临时模型名，再另存为输出模型。
temporaryModelFile = [tempname(tempdir) '.slx'];
copyfile(sourceModelFile, temporaryModelFile, 'f');
[~, temporaryModel] = fileparts(temporaryModelFile);

cleanupObject = onCleanup(@()cleanupTemporaryModel( ...
    temporaryModel, temporaryModelFile)); %#ok<NASGU>

closeModelIfLoaded(outputModel);
if isfile(outputModelFile)
    delete(outputModelFile);
end

load_system(temporaryModelFile);
save_system(temporaryModel, outputModelFile);
close_system(temporaryModel, 0);
load_system(outputModelFile);

%% 1. 删除旧的 Python 中间链路和实验记录模块

deleteBlockIfPresent([outputModel '/Camera Velocity Publisher']);
deleteBlockIfPresent([outputModel '/Watchdog and Safety']);
deleteBlockIfPresent([outputModel '/velocity_command Subscriber']);
deleteBlockIfPresent([outputModel '/Logging']);
deleteBlockIfPresent([outputModel '/Scope']);

workspaceBlocks = find_system( ...
    outputModel, ...
    'SearchDepth', 1, ...
    'BlockType', 'ToWorkspace');
for blockIndex = 1:numel(workspaceBlocks)
    delete_block(workspaceBlocks{blockIndex});
end

%% 2. 按 JointState.name 重排 FR3 七个关节

jointStateSubscriber = [outputModel '/Joint State ROS2 Subscriber'];
configureJointStateNameReordering(jointStateSubscriber);

%% 3. 重构运动学反馈：输出完整相机 Jacobian [v;omega]

oldKinematics = [outputModel '/v_measured Subscribe'];
set_param(oldKinematics, 'Name', 'Kinematics Feedback');
kinematics = [outputModel '/Kinematics Feedback'];

set_param([kinematics '/Get Jacobian'], ...
    'RigidBodyTree', 'fr3_camera_robot', ...
    'EndEffector', 'camera_link');

set_param([kinematics '/Get Transform'], ...
    'RigidBodyTree', 'fr3_camera_robot', ...
    'SourceBody', 'camera_link', ...
    'TargetBody', 'base');

kinematicsFunction = [kinematics '/MATLAB Function'];
setMatlabFunctionScript(kinematicsFunction, kinematicsFunctionCode());

set_param([kinematics '/v_camera_measured'], ...
    'Name', 'camera_twist_measured');
set_param([kinematics '/feedback_valid'], ...
    'Name', 'kinematics_valid');

add_block('simulink/Sinks/Out1', ...
    [kinematics '/J_camera'], ...
    'Port', '4', ...
    'Position', [1160 405 1190 425]);

connectPorts( ...
    kinematicsFunction, 4, ...
    [kinematics '/J_camera'], 1);

%% 4. 保留原 KF/使能逻辑，删除旧命令滤波和限幅接口

oldEstimator = [outputModel '/Planar Target EKF'];
set_param(oldEstimator, 'Name', 'Planar Target KF and Task Command');
estimator = [outputModel '/Planar Target KF and Task Command'];

% 删除原二维命令链路遗留的三个参数。新的关节命令只在最终 Guard 中
% 进行一次低通、速度限制和加速度限制。
deleteConstantBlocksByValue(estimator, { ...
    'v_xy_max', ...
    'a_xy_max', ...
    'ff_filter_tau'});

parameterVector = find_system( ...
    estimator, ...
    'SearchDepth', 1, ...
    'BlockType', 'Concatenate');
assert(numel(parameterVector) == 1, ...
    '无法唯一定位 KF 参数向量拼接块。');
set_param(parameterVector{1}, 'NumInputs', '10');

deleteAnnotationsInSubsystem(estimator);

set_param([estimator '/EKF and Controller Core'], ...
    'Name', 'KF and Task Command Core');
estimatorFunction = [estimator '/KF and Task Command Core'];
setMatlabFunctionScript(estimatorFunction, estimatorFunctionCode());

% MATLAB Function 块来自旧模型。仅替换 Script 不会自动清除
% Stateflow 中保存的固定输入尺寸；旧 parameters 仍可能保持为 [12 1]。
% 新参数向量已经删除三项旧命令参数，因此必须显式同步为 [10 1]。
setMatlabFunctionInputSize(estimatorFunction, 'parameters', [10 1]);

% 删除 ff_filter_tau 后，z 成为 MATLAB Function 的第 13 个输入。
% 显式重连，避免源模型旧端口号残留。
reconnectPorts([estimator '/z'], 1, estimatorFunction, 13);

% 外层子系统保留原端口编号，避免破坏已有诊断接口；只更新旧名称。
set_param([estimator '/v_norm_limited'], 'Name', 'v_task_raw');
set_param([estimator '/saturation_active'], 'Name', 'control_active');

%% 5. 新增完整视觉雅可比和冗余关节速度求解器

solverBlock = [outputModel '/Redundant Visual Velocity Solver'];
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    solverBlock, ...
    'Position', [1900 520 2220 950]);
setMatlabFunctionScript(solverBlock, redundantSolverFunctionCode());

solverParameters = [outputModel '/Solver Parameters'];
add_block('simulink/Sources/Constant', ...
    solverParameters, ...
    'Value', [ ...
    '[visual_damping_min;visual_damping_max;' ...
    'singularity_sigma_stop;singularity_sigma_warn;' ...
    'nullspace_posture_gain;depth_safe_min;depth_safe_max;' ...
    'depth_safety_gain;visual_min_depth]'], ...
    'Position', [1550 1040 1780 1080]);

nominalConfiguration = [outputModel '/Nominal Joint Configuration'];
add_block('simulink/Sources/Constant', ...
    nominalConfiguration, ...
    'Value', 'joint_nominal_configuration', ...
    'Position', [1550 1100 1780 1140]);

jointMinimum = [outputModel '/Joint Minimum'];
add_block('simulink/Sources/Constant', ...
    jointMinimum, ...
    'Value', 'joint_position_min', ...
    'Position', [1550 1160 1780 1200]);

jointMaximum = [outputModel '/Joint Maximum'];
add_block('simulink/Sources/Constant', ...
    jointMaximum, ...
    'Value', 'joint_position_max', ...
    'Position', [1550 1220 1780 1260]);

% 从 Outport 块读取真实端口号，避免再次把信号按函数输出顺序误接。
estimatorControllerOkPort = getOutportNumber( ...
    [estimator '/controller_ok']);
estimatorTaskVelocityPort = getOutportNumber( ...
    [estimator '/v_task_raw']);
estimatorControlActivePort = getOutportNumber( ...
    [estimator '/control_active']);

% Solver 输入顺序由 redundantSolverFunctionCode 的函数签名确定。
connectPorts(estimator, estimatorTaskVelocityPort, solverBlock, 1);
connectPorts([outputModel '/Normalized Image Coordinates'], 1, solverBlock, 2);
connectPorts([outputModel '/Message Validation'], 7, solverBlock, 3); % z
connectPorts(kinematics, 4, solverBlock, 4);                % J_camera
connectPorts([outputModel '/Message Validation'], 4, solverBlock, 5); % q
connectPorts([outputModel '/Message Validation'], 1, solverBlock, 6); % safe_valid
connectPorts(estimator, estimatorControlActivePort, solverBlock, 7);
connectPorts(estimator, estimatorControllerOkPort, solverBlock, 8);
connectPorts(kinematics, 2, solverBlock, 9);                % kinematics_valid
connectPorts(solverParameters, 1, solverBlock, 10);
connectPorts(nominalConfiguration, 1, solverBlock, 11);
connectPorts(jointMinimum, 1, solverBlock, 12);
connectPorts(jointMaximum, 1, solverBlock, 13);

%% 6. 新增唯一的最底层关节命令滤波/速度/加速度/限位保护

guardBlock = [outputModel '/Final Joint Command Guard'];
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    guardBlock, ...
    'Position', [2350 540 2660 950]);
setMatlabFunctionScript(guardBlock, jointGuardFunctionCode());

guardParameters = [outputModel '/Guard Parameters'];
add_block('simulink/Sources/Constant', ...
    guardParameters, ...
    'Value', '[Ts;joint_command_filter_tau;joint_soft_margin]', ...
    'Position', [2310 1035 2540 1075]);

jointVelocityLimit = [outputModel '/Joint Velocity Limit'];
add_block('simulink/Sources/Constant', ...
    jointVelocityLimit, ...
    'Value', 'joint_velocity_limit', ...
    'Position', [2310 1095 2540 1135]);

jointAccelerationLimit = [outputModel '/Joint Acceleration Limit'];
add_block('simulink/Sources/Constant', ...
    jointAccelerationLimit, ...
    'Value', 'joint_acceleration_limit', ...
    'Position', [2310 1155 2540 1195]);

connectPorts(solverBlock, 1, guardBlock, 1);                % qdot_raw
connectPorts([outputModel '/Message Validation'], 4, guardBlock, 2);
connectPorts([outputModel '/Message Validation'], 1, guardBlock, 3);
connectPorts(estimator, estimatorControlActivePort, guardBlock, 4);
connectPorts(solverBlock, 5, guardBlock, 5);               % solver_valid
connectPorts(guardParameters, 1, guardBlock, 6);
connectPorts(jointVelocityLimit, 1, guardBlock, 7);
connectPorts(jointAccelerationLimit, 1, guardBlock, 8);
connectPorts(jointMinimum, 1, guardBlock, 9);
connectPorts(jointMaximum, 1, guardBlock, 10);

%% 7. Simulink 直接发布 7 维关节角速度

publisher = [outputModel '/Joint Velocity Publisher'];
addJointVelocityPublisher( ...
    publisher, ...
    '/joint_velocity_example_controller/commands');
connectPorts(guardBlock, 1, publisher, 1);

%% 8. 参数、显示与保存

appendNewInitializationParameters(outputModel);

set_param(outputModel, ...
    'SolverType', 'Fixed-step', ...
    'FixedStep', 'Ts', ...
    'StopTime', 'inf');

add_block('simulink/Sinks/Display', ...
    [outputModel '/qdot command monitor'], ...
    'Position', [2920 610 3060 700]);
connectPorts(guardBlock, 1, ...
    [outputModel '/qdot command monitor'], 1);

set_param(outputModel, 'SimulationCommand', 'Update');

Simulink.BlockDiagram.arrangeSystem(outputModel);

save_system(outputModel, outputModelFile);
open_system(outputModel);

fprintf('\n已生成模型：\n  %s\n', outputModelFile);
fprintf('最终发布 Topic：\n  /joint_velocity_example_controller/commands\n');
fprintf(['首次测试：保持 controller 未激活或使用 dry-run，先检查 7 维长度、' ...
    '左右/上下方向、sigma_min 和零命令。\n\n']);

end


function sourceModelFile = findSourceModel()

buildFolder = fileparts(mfilename('fullpath'));
searchFolders = { ...
    buildFolder, ...
    fullfile(buildFolder, 'upload'), ...
    pwd};

sourceModelFile = '';
for folderIndex = 1:numel(searchFolders)
    if ~isfolder(searchFolders{folderIndex})
        continue;
    end

    candidates = dir(fullfile( ...
        searchFolders{folderIndex}, ...
        'single_camera_xy_tracking_isnew*.slx'));

    if ~isempty(candidates)
        sourceModelFile = fullfile( ...
            candidates(1).folder, ...
            candidates(1).name);
        break;
    end
end

assert(~isempty(sourceModelFile), ...
    ['没有找到 single_camera_xy_tracking_isnew*.slx。' ...
     '请把源模型路径作为输入传给 build 函数。']);

end


function cleanupTemporaryModel(temporaryModel, temporaryModelFile)

closeModelIfLoaded(temporaryModel);
if isfile(temporaryModelFile)
    delete(temporaryModelFile);
end

end


function closeModelIfLoaded(modelName)

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end

end


function deleteBlockIfPresent(blockPath)

if getSimulinkBlockHandle(blockPath) ~= -1
    delete_block(blockPath);
end

end


function deleteConstantBlocksByValue(subsystemPath, valuesToDelete)

constantBlocks = find_system( ...
    subsystemPath, ...
    'SearchDepth', 1, ...
    'BlockType', 'Constant');

for blockIndex = 1:numel(constantBlocks)
    blockValue = strtrim(get_param(constantBlocks{blockIndex}, 'Value'));
    if any(strcmp(blockValue, valuesToDelete))
        delete_block(constantBlocks{blockIndex});
    end
end

end


function deleteAnnotationsInSubsystem(subsystemPath)

annotationHandles = find_system( ...
    subsystemPath, ...
    'SearchDepth', 1, ...
    'FindAll', 'on', ...
    'Type', 'annotation');

for annotationIndex = 1:numel(annotationHandles)
    annotationObject = get_param( ...
        annotationHandles(annotationIndex), ...
        'Object');
    delete(annotationObject);
end

end


function setMatlabFunctionScript(blockPath, codeText)

stateflowRoot = sfroot;
chartObject = stateflowRoot.find( ...
    '-isa', 'Stateflow.EMChart', ...
    'Path', blockPath);

assert(numel(chartObject) == 1, ...
    '无法唯一定位 MATLAB Function：%s', blockPath);

chartObject.Script = char(codeText);

end


function setMatlabFunctionInputSize(blockPath, inputName, inputSize)

stateflowRoot = sfroot;
chartObject = stateflowRoot.find( ...
    '-isa', 'Stateflow.EMChart', ...
    'Path', blockPath);

assert(numel(chartObject) == 1, ...
    '无法唯一定位 MATLAB Function：%s', blockPath);

dataObjects = chartObject.Inputs;
nameMatches = false(size(dataObjects));
for dataIndex = 1:numel(dataObjects)
    nameMatches(dataIndex) = strcmp(dataObjects(dataIndex).Name, inputName);
end
inputData = dataObjects(nameMatches);

assert(numel(inputData) == 1, ...
    '无法唯一定位 MATLAB Function 输入 %s：%s', inputName, blockPath);
assert(isnumeric(inputSize) && numel(inputSize) == 2 && ...
    all(isfinite(inputSize)) && all(inputSize >= 1) && ...
    all(inputSize == floor(inputSize)), ...
    'MATLAB Function 输入尺寸无效：%s', inputName);

inputData.Props.Array.Size = sprintf('[%d %d]', inputSize(1), inputSize(2));

end


function reconnectPorts(sourceBlock, sourcePort, destinationBlock, destinationPort)

sourceHandles = get_param(sourceBlock, 'PortHandles');
assert(numel(sourceHandles.Outport) >= sourcePort, ...
    '源块端口不存在：%s/%d', sourceBlock, sourcePort);

oldLine = get_param(sourceHandles.Outport(sourcePort), 'Line');
if oldLine ~= -1
    delete_line(oldLine);
end

connectPorts(sourceBlock, sourcePort, destinationBlock, destinationPort);

end


function configureJointStateNameReordering(subsystemPath)

selector = [subsystemPath '/Select Joint Arrays'];
assert(getSimulinkBlockHandle(selector) ~= -1, ...
    '找不到 JointState Bus Selector：%s', selector);

set_param(selector, 'Name', 'Select Joint State Fields');
selector = [subsystemPath '/Select Joint State Fields'];
set_param(selector, ...
    'OutputSignals', [ ...
    'name,name_SL_Info,' ...
    'position,position_SL_Info,' ...
    'velocity,velocity_SL_Info']);

unpackFunction = [subsystemPath '/Unpack'];
setMatlabFunctionScript(unpackFunction, jointStateUnpackFunctionCode());

% 替换函数签名后，清除旧的四输入连线并按新八输入接口显式重连。
deleteAllInputLines(unpackFunction);

subscribe = [subsystemPath '/Subscribe'];
clockBlock = [subsystemPath '/Clock'];

connectPorts(selector, 1, unpackFunction, 1);  % name
connectPorts(selector, 2, unpackFunction, 2);  % name_SL_Info
connectPorts(selector, 3, unpackFunction, 3);  % position
connectPorts(selector, 4, unpackFunction, 4);  % position_SL_Info
connectPorts(selector, 5, unpackFunction, 5);  % velocity
connectPorts(selector, 6, unpackFunction, 6);  % velocity_SL_Info
connectPorts(subscribe, 1, unpackFunction, 7); % IsNew
connectPorts(clockBlock, 1, unpackFunction, 8); % current time

end


function deleteAllInputLines(blockPath)

portHandles = get_param(blockPath, 'PortHandles');
for portIndex = 1:numel(portHandles.Inport)
    lineHandle = get_param(portHandles.Inport(portIndex), 'Line');
    if lineHandle ~= -1
        delete_line(lineHandle);
    end
end

end


function portNumber = getOutportNumber(outportBlock)

assert(getSimulinkBlockHandle(outportBlock) ~= -1, ...
    '找不到 Outport 块：%s', outportBlock);

portNumber = str2double(get_param(outportBlock, 'Port'));
assert(isfinite(portNumber) && portNumber >= 1 && ...
    portNumber == floor(portNumber), ...
    'Outport 端口号无效：%s', outportBlock);

end


function connectPorts(sourceBlock, sourcePort, destinationBlock, destinationPort)

sourceHandles = get_param(sourceBlock, 'PortHandles');
destinationHandles = get_param(destinationBlock, 'PortHandles');

assert(numel(sourceHandles.Outport) >= sourcePort, ...
    '源块端口不存在：%s/%d', sourceBlock, sourcePort);
assert(numel(destinationHandles.Inport) >= destinationPort, ...
    '目标块端口不存在：%s/%d', destinationBlock, destinationPort);

sourceParent = get_param(sourceBlock, 'Parent');
destinationParent = get_param(destinationBlock, 'Parent');
assert(strcmp(sourceParent, destinationParent), ...
    '连线两端不在同一层：%s -> %s', sourceBlock, destinationBlock);

add_line( ...
    sourceParent, ...
    sourceHandles.Outport(sourcePort), ...
    destinationHandles.Inport(destinationPort), ...
    'autorouting', 'on');

end


function addJointVelocityPublisher(subsystemPath, topicName)

add_block('simulink/Ports & Subsystems/Subsystem', ...
    subsystemPath, ...
    'Position', [2760 540 2930 720]);

deleteBlockIfPresent([subsystemPath '/In1']);
deleteBlockIfPresent([subsystemPath '/Out1']);

inport = [subsystemPath '/qdot_command'];
add_block('simulink/Sources/In1', ...
    inport, ...
    'Position', [30 110 60 130]);

blankMessage = [subsystemPath '/Blank Message'];
add_block('ros2lib/Blank Message', ...
    blankMessage, ...
    'Position', [30 25 155 65]);
set_param(blankMessage, ...
    'messageClass', 'Message', ...
    'entityType', 'std_msgs/Float64MultiArray', ...
    'messageType', 'std_msgs/Float64MultiArray', ...
    'SampleTime', 'Ts');

packFunction = [subsystemPath '/Pack Seven Joint Velocities'];
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    packFunction, ...
    'Position', [110 95 300 155]);
setMatlabFunctionScript(packFunction, publisherPackFunctionCode());

busAssignment = [subsystemPath '/Assign Data'];
add_block('simulink/Signal Routing/Bus Assignment', ...
    busAssignment, ...
    'AssignedSignals', ...
    'data,data_SL_Info.CurrentLength,data_SL_Info.ReceivedLength', ...
    'Position', [350 30 485 135]);

publishBlock = [subsystemPath '/Publish'];
add_block('ros2lib/Publish', ...
    publishBlock, ...
    'Position', [550 50 690 115]);
set_param(publishBlock, ...
    'topicSource', 'Specify your own', ...
    'topic', topicName, ...
    'messageType', 'std_msgs/Float64MultiArray', ...
    'QOSHistory', 'Keep last', ...
    'QOSDepth', '1', ...
    'QOSReliability', 'Reliable', ...
    'QOSDurability', 'Volatile');

connectPorts(inport, 1, packFunction, 1);
connectPorts(blankMessage, 1, busAssignment, 1);
connectPorts(packFunction, 1, busAssignment, 2);
connectPorts(packFunction, 2, busAssignment, 3);
connectPorts(packFunction, 3, busAssignment, 4);
connectPorts(busAssignment, 1, publishBlock, 1);

end


function appendNewInitializationParameters(modelName)

oldInitialization = get_param(modelName, 'InitFcn');

newInitialization = strjoin([ ...
    "% Direct joint-velocity refactor defaults", ...
    "if ~exist('visual_damping_min','var'), visual_damping_min = 0.015; end", ...
    "if ~exist('visual_damping_max','var'), visual_damping_max = 0.20; end", ...
    "if ~exist('singularity_sigma_stop','var'), singularity_sigma_stop = 0.025; end", ...
    "if ~exist('singularity_sigma_warn','var'), singularity_sigma_warn = 0.080; end", ...
    "if ~exist('nullspace_posture_gain','var'), nullspace_posture_gain = 0.08; end", ...
    "if ~exist('depth_safe_min','var'), depth_safe_min = 0.30; end", ...
    "if ~exist('depth_safe_max','var'), depth_safe_max = 0.80; end", ...
    "if ~exist('depth_safety_gain','var'), depth_safety_gain = 0.50; end", ...
    "if ~exist('visual_min_depth','var'), visual_min_depth = 0.10; end", ...
    "if ~exist('joint_command_filter_tau','var'), joint_command_filter_tau = 0.040; end", ...
    "if ~exist('joint_soft_margin','var'), joint_soft_margin = 0.15; end", ...
    "if ~exist('joint_nominal_configuration','var'), joint_nominal_configuration = [0;-pi/4;0;-3*pi/4;0;pi/2;pi/4]; end", ...
    "% Franka 官方建议的矩形位置工作区，而不是硬件绝对边界。", ...
    "if ~exist('joint_position_min','var'), joint_position_min = [-2.3476;-1.5454;-2.4937;-2.7714;-2.5100;0.7773;-2.7045]; end", ...
    "if ~exist('joint_position_max','var'), joint_position_max = [2.3476;1.5454;2.4937;-0.4226;2.5100;4.2841;2.7045]; end", ...
    "% 初次真机验证使用保守的软件速度/加速度，不等同于 FR3 硬件极限。", ...
    "if ~exist('joint_velocity_limit','var'), joint_velocity_limit = [0.50;0.50;0.50;0.50;0.75;0.75;0.75]; end", ...
    "if ~exist('joint_acceleration_limit','var'), joint_acceleration_limit = 1.50*ones(7,1); end" ...
    ], newline);

set_param(modelName, ...
    'InitFcn', sprintf('%s\n\n%s', oldInitialization, newInitialization));

end


function codeText = jointStateUnpackFunctionCode()

codeText = strjoin([ ...
"function [joint_position,joint_count,joint_velocity,joint_age] = fcn( ...", ...
"    name,name_info,position,position_info,velocity,velocity_info,is_new,t)", ...
"%#codegen", ...
"% ROS JointState 的 name、position、velocity 使用相同索引。", ...
"% 仅当 fr3_joint1...fr3_joint7 均唯一存在且数组索引完整时才更新输出。", ...
"", ...
"persistent last_q last_dq last_count last_time", ...
"if isempty(last_count)", ...
"    last_q=zeros(7,1); last_dq=zeros(7,1);", ...
"    last_count=0.0; last_time=-1.0e6;", ...
"end", ...
"", ...
"if is_new", ...
"    last_q=zeros(7,1); last_dq=zeros(7,1);", ...
"    last_count=0.0; last_time=t;", ...
"", ...
"    name_count=min(double(name_info.CurrentLength),double(numel(name)));", ...
"    position_count=min(double(position_info.CurrentLength),double(numel(position)));", ...
"    velocity_count=min(double(velocity_info.CurrentLength),double(numel(velocity)));", ...
"", ...
"    arrays_not_truncated = ...", ...
"        double(name_info.CurrentLength)==double(name_info.ReceivedLength) && ...", ...
"        double(position_info.CurrentLength)==double(position_info.ReceivedLength) && ...", ...
"        double(velocity_info.CurrentLength)==double(velocity_info.ReceivedLength);", ...
"    message_shape_ok = arrays_not_truncated && name_count>=7.0 && ...", ...
"        position_count>=7.0 && velocity_count>=7.0;", ...
"", ...
"    if message_shape_ok", ...
"        expected_names=uint8([ ...", ...
"            'fr3_joint1';'fr3_joint2';'fr3_joint3';'fr3_joint4'; ...", ...
"            'fr3_joint5';'fr3_joint6';'fr3_joint7']);", ...
"        matched=false(7,1); source_order=zeros(7,1); names_valid=true;", ...
"", ...
"        for source_index=1:numel(name)", ...
"            if double(source_index)<=name_count", ...
"                character_count=min( ...", ...
"                    double(name(source_index).data_SL_Info.CurrentLength), ...", ...
"                    double(numel(name(source_index).data)));", ...
"                string_not_truncated = ...", ...
"                    double(name(source_index).data_SL_Info.CurrentLength)== ...", ...
"                    double(name(source_index).data_SL_Info.ReceivedLength);", ...
"", ...
"                if string_not_truncated && character_count==10.0", ...
"                    for expected_index=1:7", ...
"                        same_name=true;", ...
"                        for character_index=1:10", ...
"                            if name(source_index).data(character_index)~= ...", ...
"                                    expected_names(expected_index,character_index)", ...
"                                same_name=false;", ...
"                            end", ...
"                        end", ...
"", ...
"                        if same_name", ...
"                            if matched(expected_index)", ...
"                                names_valid=false;", ...
"                            else", ...
"                                matched(expected_index)=true;", ...
"                                source_order(expected_index)=double(source_index);", ...
"                            end", ...
"                        end", ...
"                    end", ...
"                end", ...
"            end", ...
"        end", ...
"", ...
"        names_valid=names_valid && all(matched);", ...
"        indices_valid=names_valid && all(source_order>=1.0) && ...", ...
"            all(source_order<=position_count) && ...", ...
"            all(source_order<=velocity_count);", ...
"", ...
"        if indices_valid", ...
"            for joint_index=1:7", ...
"                source_index=source_order(joint_index);", ...
"                last_q(joint_index)=position(source_index);", ...
"                last_dq(joint_index)=velocity(source_index);", ...
"            end", ...
"", ...
"            values_valid=all(isfinite(last_q(:))) && all(isfinite(last_dq(:)));", ...
"            if values_valid", ...
"                last_count=7.0;", ...
"            else", ...
"                last_q=zeros(7,1); last_dq=zeros(7,1);", ...
"            end", ...
"        end", ...
"    end", ...
"end", ...
"", ...
"joint_position=last_q; joint_count=last_count;", ...
"joint_velocity=last_dq; joint_age=max(0.0,t-last_time);", ...
"end" ...
], newline);

end


function codeText = kinematicsFunctionCode()

codeText = strjoin([ ...
"function [camera_twist_measured,kinematics_valid,T_camera2base_out,J_camera] = fcn( ...", ...
"    J_camera_base_wv,qdot_measured,T_camera2base,joint_count,joint_age,feedback_timeout)", ...
"%#codegen", ...
"% Get Jacobian 输出为 Base 表达的 [omega;v]。", ...
"% 本函数输出相机光学坐标系表达的 [v;omega] 和完整 6x7 Jacobian。", ...
"", ...
"camera_twist_measured = zeros(6,1);", ...
"kinematics_valid = false;", ...
"T_camera2base_out = eye(4);", ...
"J_camera = zeros(6,7);", ...
"qdot_measured = reshape(qdot_measured,7,1);", ...
"", ...
"input_ok = joint_count >= 7 && isfinite(joint_age) && ...", ...
"    isfinite(feedback_timeout) && feedback_timeout > 0.0 && ...", ...
"    joint_age >= 0.0 && joint_age <= feedback_timeout && ...", ...
"    all(isfinite(qdot_measured(:))) && ...", ...
"    isequal(size(J_camera_base_wv),[6 7]) && ...", ...
"    all(isfinite(J_camera_base_wv(:))) && ...", ...
"    isequal(size(T_camera2base),[4 4]) && ...", ...
"    all(isfinite(T_camera2base(:)));", ...
"", ...
"if ~input_ok", ...
"    return;", ...
"end", ...
"", ...
"R_base_camera = T_camera2base(1:3,1:3);", ...
"pose_ok = norm(R_base_camera'*R_base_camera-eye(3),'fro') < 1e-3 && ...", ...
"    abs(det(R_base_camera)-1.0) < 1e-3 && ...", ...
"    norm(T_camera2base(4,:)-[0 0 0 1]) < 1e-6;", ...
"if ~pose_ok", ...
"    return;", ...
"end", ...
"", ...
"% 先把 [omega;v] 改成统一的 [v;omega]。", ...
"J_base_vw = J_camera_base_wv([4 5 6 1 2 3],:);", ...
"R_camera_base = R_base_camera';", ...
"rotation6 = [R_camera_base zeros(3);zeros(3) R_camera_base];", ...
"", ...
"% Jacobian 已经是在 camera_link 原点计算，因此这里只改变表达坐标系，", ...
"% 不再重复加入相机安装平移偏置。", ...
"J_camera = rotation6*J_base_vw;", ...
"camera_twist_measured = J_camera*qdot_measured;", ...
"T_camera2base_out = T_camera2base;", ...
"", ...
"kinematics_valid = all(isfinite(J_camera(:))) && ...", ...
"    all(isfinite(camera_twist_measured(:)));", ...
"if ~kinematics_valid", ...
"    J_camera = zeros(6,7);", ...
"    camera_twist_measured = zeros(6,1);", ...
"end", ...
"end" ...
], newline);

end


function codeText = estimatorFunctionCode()

codeText = strjoin([ ...
"function [ekf_state,ekf_covariance,v_target_hat,v_p,v_ff,v_task_raw,v_issued,camera_velocity,control_active,acceleration_active,ekf_initialized,innovation_nis,measurement_accepted,controller_ok] = fcn( ...", ...
"    T_camera2base,z_meas,e,safe_valid,target_is_new,R_ekf,P0,Q_ekf,parameters,required_valid_frames,measurement_reset_timeout,target_visible,z)", ...
"%#codegen", ...
"% 四状态匀速 KF：[X_B;Y_B;Vx_B;Vy_B]。", ...
"% 原消息、目标、P/FF 和总控制使能关系保持不变。", ...
"% v_task_raw 是未滤波、未限幅的二维相机平移速度请求。", ...
"", ...
"persistent x_hat P e_hold z_hold time_since_accepted initialized", ...
"persistent valid_streak ekf_ready time_since_visible target_tracking_active", ...
"", ...
"if isempty(initialized)", ...
"    x_hat = zeros(4,1); P = P0; e_hold = zeros(2,1); z_hold = 0.0;", ...
"    time_since_accepted = 0.0; initialized = false;", ...
"    valid_streak = 0.0; ekf_ready = false;", ...
"    time_since_visible = inf; target_tracking_active = false;", ...
"end", ...
"", ...
"ekf_state = x_hat; ekf_covariance = P; v_target_hat = zeros(2,1);", ...
"v_p = zeros(2,1); v_ff = zeros(2,1); v_task_raw = zeros(2,1);", ...
"v_issued = zeros(2,1); camera_velocity = zeros(6,1);", ...
"control_active = false; acceleration_active = false;", ...
"ekf_initialized = initialized && ekf_ready; innovation_nis = NaN;", ...
"measurement_accepted = false; controller_ok = false;", ...
"", ...
"if numel(parameters) < 10", ...
"    x_hat=zeros(4,1); P=P0; e_hold=zeros(2,1); z_hold=0.0;", ...
"    time_since_accepted=0.0; initialized=false; valid_streak=0.0;", ...
"    ekf_ready=false; time_since_visible=inf; target_tracking_active=false;", ...
"    ekf_state=x_hat; ekf_covariance=P; ekf_initialized=false; return;", ...
"end", ...
"", ...
"Ts=parameters(1); Z_hat=parameters(2); Kpx=parameters(3); Kpy=parameters(4);", ...
"k_ff=parameters(5); gate=parameters(6);", ...
"enable_p=parameters(7)>0.5; enable_ff=parameters(8)>0.5;", ...
"controller_enable=parameters(9)>0.5;", ...
"target_lost_timeout=parameters(10);", ...
"if target_lost_timeout<=0.0, target_lost_timeout=0.10; end", ...
"safe_valid=safe_valid>0.5; target_visible=target_visible>0.5;", ...
"target_is_new=target_is_new>0.5;", ...
"required_valid_frames=max(1.0,floor(required_valid_frames));", ...
"", ...
"parameter_ok = all(isfinite(parameters(1:10))) && ...", ...
"    isfinite(required_valid_frames) && isfinite(measurement_reset_timeout) && ...", ...
"    Ts>0.0 && Z_hat>0.0 && gate>0.0 && measurement_reset_timeout>=Ts && ...", ...
"    target_lost_timeout>=Ts && isequal(size(R_ekf),[2 2]) && ...", ...
"    isequal(size(P0),[4 4]) && isequal(size(Q_ekf),[4 4]) && ...", ...
"    all(isfinite(R_ekf(:))) && all(isfinite(P0(:))) && all(isfinite(Q_ekf(:)));", ...
"if ~parameter_ok", ...
"    x_hat=zeros(4,1); P=P0; e_hold=zeros(2,1); z_hold=0.0;", ...
"    time_since_accepted=0.0; initialized=false; valid_streak=0.0;", ...
"    ekf_ready=false; time_since_visible=inf; target_tracking_active=false;", ...
"    ekf_state=x_hat; ekf_covariance=P; ekf_initialized=false; return;", ...
"end", ...
"", ...
"if ~(isfinite(z_hold) && z_hold>0.0)", ...
"    z_hold=max(Z_hat,0.10);", ...
"end", ...
"", ...
"F=[1 0 Ts 0;0 1 0 Ts;0 0 1 0;0 0 0 1];", ...
"H=[1 0 0 0;0 1 0 0]; I4=eye(4);", ...
"", ...
"pose_matrix_ok=isequal(size(T_camera2base),[4 4]) && ...", ...
"    all(isfinite(T_camera2base(:)));", ...
"R_base_camera=eye(3); t_base_camera=zeros(3,1); pose_ok=false;", ...
"if pose_matrix_ok", ...
"    R_candidate=T_camera2base(1:3,1:3);", ...
"    t_candidate=T_camera2base(1:3,4);", ...
"    pose_ok=norm(R_candidate'*R_candidate-eye(3),'fro')<1e-3 && ...", ...
"        abs(det(R_candidate)-1.0)<1e-3 && ...", ...
"        norm(T_camera2base(4,:)-[0 0 0 1])<1e-6 && ...", ...
"        all(isfinite(t_candidate));", ...
"    if pose_ok, R_base_camera=R_candidate; t_base_camera=t_candidate; end", ...
"end", ...
"", ...
"measurement_vectors_ok=numel(z_meas)==2 && numel(e)==2 && ...", ...
"    all(isfinite(z_meas(:))) && all(isfinite(e(:)));", ...
"vision_safe=safe_valid && measurement_vectors_ok;", ...
"", ...
"if ~vision_safe", ...
"    time_since_visible=inf; target_tracking_active=false; e_hold=zeros(2,1);", ...
"elseif target_is_new && target_visible", ...
"    time_since_visible=0.0; target_tracking_active=true; e_hold=reshape(e,2,1);", ...
"    if isfinite(z) && z>1e-4, z_hold=z; end", ...
"else", ...
"    time_since_visible=min(time_since_visible+Ts,target_lost_timeout+Ts);", ...
"    if time_since_visible>=target_lost_timeout", ...
"        target_tracking_active=false; e_hold=zeros(2,1);", ...
"    end", ...
"end", ...
"", ...
"measurement_available=vision_safe && target_is_new && target_visible && ...", ...
"    pose_ok && isfinite(z) && z>1e-4;", ...
"z_base=zeros(2,1); R_measurement_base=R_ekf;", ...
"if measurement_available", ...
"    p_target_camera=[z_meas(1);z_meas(2);z];", ...
"    p_target_base=R_base_camera*p_target_camera+t_base_camera;", ...
"    z_base=p_target_base(1:2);", ...
"    measurement_rotation=R_base_camera(1:2,1:2);", ...
"    R_measurement_base=measurement_rotation*R_ekf*measurement_rotation';", ...
"    R_measurement_base=0.5*(R_measurement_base+R_measurement_base');", ...
"    measurement_available=all(isfinite(z_base(:))) && ...", ...
"        all(isfinite(R_measurement_base(:)));", ...
"end", ...
"", ...
"if ~initialized", ...
"    if measurement_available", ...
"        x_hat=[z_base(1);z_base(2);0;0]; P=P0;", ...
"        initialized=true; measurement_accepted=true;", ...
"    end", ...
"else", ...
"    x_pred=F*x_hat; P_pred=F*P*F'+Q_ekf; P_pred=0.5*(P_pred+P_pred');", ...
"    x_hat=x_pred; P=P_pred;", ...
"    if measurement_available", ...
"        innovation=z_base-H*x_pred; S=H*P_pred*H'+R_measurement_base;", ...
"        if all(isfinite(S(:))) && rcond(S)>1e-12", ...
"            innovation_nis=innovation'*(S\innovation);", ...
"        else", ...
"            innovation_nis=inf;", ...
"        end", ...
"        if isfinite(innovation_nis) && innovation_nis<=gate", ...
"            K=(P_pred*H')/S; x_hat=x_pred+K*innovation; A=I4-K*H;", ...
"            P=A*P_pred*A'+K*R_measurement_base*K';", ...
"            P=0.5*(P+P'); measurement_accepted=true;", ...
"        end", ...
"    end", ...
"end", ...
"", ...
"if measurement_accepted", ...
"    time_since_accepted=0.0;", ...
"    valid_streak=min(valid_streak+1.0,required_valid_frames);", ...
"    if valid_streak>=required_valid_frames, ekf_ready=true; end", ...
"else", ...
"    if target_is_new && ~ekf_ready, valid_streak=0.0; end", ...
"    time_since_accepted=time_since_accepted+Ts;", ...
"end", ...
"", ...
"ekf_ok=all(isfinite(x_hat(:))) && all(isfinite(P(:))) && ...", ...
"    all(diag(P)>=0.0) && norm(P-P','fro')<1e-6;", ...
"if time_since_accepted>=measurement_reset_timeout || ~ekf_ok", ...
"    x_hat=zeros(4,1); P=P0; time_since_accepted=0.0; initialized=false;", ...
"    valid_streak=0.0; ekf_ready=false; measurement_accepted=false;", ...
"end", ...
"", ...
"ekf_state=x_hat; ekf_covariance=P;", ...
"if initialized && ekf_ready", ...
"    v_target_hat=x_hat(3:4);", ...
"else", ...
"    v_target_hat=zeros(2,1); ekf_state(3:4)=zeros(2,1);", ...
"end", ...
"ekf_initialized=initialized && ekf_ready;", ...
"", ...
"if controller_enable && enable_p && vision_safe && target_tracking_active", ...
"    v_p=z_hold*[Kpx*e_hold(1);Kpy*e_hold(2)];", ...
"else", ...
"    v_p=zeros(2,1);", ...
"end", ...
"", ...
"v_target_camera_xy=zeros(2,1);", ...
"if initialized && ekf_ready && pose_ok", ...
"    v_target_base_3d=[x_hat(3);x_hat(4);0];", ...
"    v_target_camera_3d=R_base_camera'*v_target_base_3d;", ...
"    v_target_camera_xy=v_target_camera_3d(1:2);", ...
"end", ...
"if controller_enable && enable_ff && vision_safe && initialized && ekf_ready && pose_ok", ...
"    v_ff=k_ff*v_target_camera_xy;", ...
"else", ...
"    v_ff=zeros(2,1);", ...
"end", ...
"", ...
"v_task_raw=v_p+v_ff; v_issued=v_task_raw;", ...
"camera_velocity=[v_task_raw;0;0;0;0];", ...
"control_active=controller_enable && vision_safe && ...", ...
"    ((enable_p && target_tracking_active) || ...", ...
"     (enable_ff && initialized && ekf_ready && pose_ok));", ...
"acceleration_active=false;", ...
"", ...
"controller_ok=all(isfinite(v_p(:))) && all(isfinite(v_ff(:))) && ...", ...
"    all(isfinite(v_task_raw(:)));", ...
"if ~controller_ok", ...
"    v_p=zeros(2,1); v_ff=zeros(2,1); v_task_raw=zeros(2,1);", ...
"    v_issued=zeros(2,1); camera_velocity=zeros(6,1);", ...
"    control_active=false; e_hold=zeros(2,1);", ...
"    time_since_visible=inf; target_tracking_active=false;", ...
"end", ...
"end" ...
], newline);

end


function codeText = redundantSolverFunctionCode()

codeText = strjoin([ ...
"function [qdot_raw,sigma_min,damping_used,singularity_scale,solver_valid] = fcn( ...", ...
"    v_task_xy,e,z,J_camera,q,safe_valid,control_active,controller_ok, ...", ...
"    kinematics_valid,solver_parameters,q_nominal,q_min,q_max)", ...
"%#codegen", ...
"% J_camera：相机光学坐标系表达、顺序为 [vx;vy;vz;wx;wy;wz]。", ...
"% 主任务只有图像中心 2 维约束，关节求解可自然使用完整 6 维相机运动。", ...
"", ...
"persistent feature_hold depth_hold", ...
"if isempty(depth_hold)", ...
"    feature_hold=zeros(2,1); depth_hold=0.50;", ...
"end", ...
"", ...
"qdot_raw=zeros(7,1); sigma_min=0.0; damping_used=0.0;", ...
"singularity_scale=0.0; solver_valid=false;", ...
"q=reshape(q,7,1); q_nominal=reshape(q_nominal,7,1);", ...
"q_min=reshape(q_min,7,1); q_max=reshape(q_max,7,1);", ...
"", ...
"input_ok=numel(v_task_xy)==2 && numel(e)==2 && ...", ...
"    isequal(size(J_camera),[6 7]) && numel(solver_parameters)>=9 && ...", ...
"    all(isfinite(v_task_xy(:))) && all(isfinite(e(:))) && ...", ...
"    all(isfinite(J_camera(:))) && all(isfinite(q(:))) && ...", ...
"    all(isfinite(q_nominal(:))) && all(isfinite(q_min(:))) && ...", ...
"    all(isfinite(q_max(:))) && all(q_max>q_min) && ...", ...
"    all(isfinite(solver_parameters(1:9)));", ...
"if ~input_ok", ...
"    feature_hold=zeros(2,1); depth_hold=0.50; return;", ...
"end", ...
"", ...
"lambda_min=solver_parameters(1); lambda_max=solver_parameters(2);", ...
"sigma_stop=solver_parameters(3); sigma_warn=solver_parameters(4);", ...
"posture_gain=solver_parameters(5); depth_min=solver_parameters(6);", ...
"depth_max=solver_parameters(7); depth_gain=solver_parameters(8);", ...
"minimum_depth=solver_parameters(9);", ...
"parameter_ok=lambda_min>0.0 && lambda_max>=lambda_min && ...", ...
"    sigma_stop>=0.0 && sigma_warn>sigma_stop && posture_gain>=0.0 && ...", ...
"    depth_min>minimum_depth && depth_max>depth_min && ...", ...
"    depth_gain>=0.0 && minimum_depth>0.0;", ...
"if ~parameter_ok", ...
"    feature_hold=zeros(2,1); depth_hold=0.50; return;", ...
"end", ...
"", ...
"if safe_valid && isfinite(z) && z>minimum_depth", ...
"    feature_hold=reshape(e,2,1); depth_hold=z;", ...
"elseif ~safe_valid", ...
"    feature_hold=zeros(2,1); depth_hold=max(depth_min,minimum_depth);", ...
"end", ...
"", ...
"singular_values=svd(J_camera);", ...
"sigma_min=singular_values(6);", ...
"if sigma_min<=sigma_stop", ...
"    singularity_scale=0.0; damping_used=lambda_max;", ...
"elseif sigma_min>=sigma_warn", ...
"    singularity_scale=1.0; damping_used=lambda_min;", ...
"else", ...
"    ratio=(sigma_min-sigma_stop)/(sigma_warn-sigma_stop);", ...
"    singularity_scale=ratio*ratio*(3.0-2.0*ratio);", ...
"    damping_used=lambda_max-(lambda_max-lambda_min)*singularity_scale;", ...
"end", ...
"", ...
"solver_valid=isfinite(sigma_min) && isfinite(damping_used) && ...", ...
"    isfinite(singularity_scale);", ...
"if ~solver_valid", ...
"    qdot_raw=zeros(7,1); return;", ...
"end", ...
"", ...
"if ~(safe_valid && control_active && controller_ok && kinematics_valid)", ...
"    qdot_raw=zeros(7,1); return;", ...
"end", ...
"", ...
"x=feature_hold(1); y=feature_hold(2); Z=max(depth_hold,minimum_depth);", ...
"L=[-1.0/Z 0 x/Z x*y -(1.0+x*x) y; ...", ...
"    0 -1.0/Z y/Z 1.0+y*y -x*y -x];", ...
"J_image=L*J_camera;", ...
"normal_matrix=J_image*J_image'+damping_used*damping_used*eye(2);", ...
"if ~(all(isfinite(normal_matrix(:))) && rcond(normal_matrix)>1e-12)", ...
"    solver_valid=false; qdot_raw=zeros(7,1); return;", ...
"end", ...
"", ...
"J_image_damped=J_image'/normal_matrix;", ...
"feature_rate_command=-(reshape(v_task_xy,2,1)/Z);", ...
"qdot_task=J_image_damped*feature_rate_command;", ...
"N_image=eye(7)-J_image_damped*J_image;", ...
"", ...
"% 简单、低参数的关节中心和软限位回避种子。", ...
"joint_range=q_max-q_min;", ...
"posture_error=(q-q_nominal)./(0.5*joint_range);", ...
"qdot_seed=-posture_gain*posture_error;", ...
"soft_zone=0.12*joint_range;", ...
"for joint_index=1:7", ...
"    lower_soft=q_min(joint_index)+soft_zone(joint_index);", ...
"    upper_soft=q_max(joint_index)-soft_zone(joint_index);", ...
"    if q(joint_index)<lower_soft", ...
"        normalized_distance=(lower_soft-q(joint_index))/soft_zone(joint_index);", ...
"        qdot_seed(joint_index)=qdot_seed(joint_index)+ ...", ...
"            2.0*posture_gain*normalized_distance*normalized_distance;", ...
"    elseif q(joint_index)>upper_soft", ...
"        normalized_distance=(q(joint_index)-upper_soft)/soft_zone(joint_index);", ...
"        qdot_seed(joint_index)=qdot_seed(joint_index)- ...", ...
"            2.0*posture_gain*normalized_distance*normalized_distance;", ...
"    end", ...
"end", ...
"qdot_null=N_image*qdot_seed;", ...
"", ...
"% 深度只在安全区之外工作，并投影到图像主任务零空间。", ...
"depth_rate_command=0.0;", ...
"if Z<depth_min", ...
"    depth_rate_command=depth_gain*(depth_min-Z);", ...
"elseif Z>depth_max", ...
"    depth_rate_command=-depth_gain*(Z-depth_max);", ...
"end", ...
"L_depth=[0 0 -1.0 -Z*y Z*x 0];", ...
"J_depth=L_depth*J_camera;", ...
"J_depth_null=J_depth*N_image;", ...
"depth_denominator=J_depth_null*J_depth_null'+damping_used*damping_used;", ...
"qdot_depth=zeros(7,1);", ...
"if depth_rate_command~=0.0 && isfinite(depth_denominator) && depth_denominator>1e-12", ...
"    qdot_depth=N_image*J_depth'*(depth_rate_command/depth_denominator);", ...
"end", ...
"", ...
"% 奇异度缩放作用于主任务、零空间姿态和深度任务的总和。", ...
"% sigma_min<=sigma_stop 时三类运动均平滑降为零。", ...
"qdot_raw=singularity_scale*(qdot_task+qdot_null+qdot_depth);", ...
"solver_valid=all(isfinite(qdot_raw(:)));", ...
"if ~solver_valid, qdot_raw=zeros(7,1); end", ...
"end" ...
], newline);

end


function codeText = jointGuardFunctionCode()

codeText = strjoin([ ...
"function [qdot_command,velocity_scale,acceleration_scale,position_scale,guard_valid] = fcn( ...", ...
"    qdot_raw,q,safe_valid,control_active,solver_valid,guard_parameters, ...", ...
"    qdot_limit,qddot_limit,q_min,q_max)", ...
"%#codegen", ...
"% 全系统唯一的最终关节命令处理：", ...
"% 一阶低通 -> 整体速度缩放 -> 整体加速度缩放 -> 软位置边界。", ...
"% 所有缩放均对 7 维向量同比例处理，不逐关节裁剪控制方向。", ...
"", ...
"persistent filtered_velocity previous_command initialized", ...
"if isempty(initialized)", ...
"    filtered_velocity=zeros(7,1); previous_command=zeros(7,1);", ...
"    initialized=true;", ...
"end", ...
"", ...
"qdot_command=zeros(7,1); velocity_scale=0.0; acceleration_scale=0.0;", ...
"position_scale=0.0; guard_valid=false;", ...
"qdot_raw=reshape(qdot_raw,7,1); q=reshape(q,7,1);", ...
"qdot_limit=reshape(qdot_limit,7,1);", ...
"qddot_limit=reshape(qddot_limit,7,1);", ...
"q_min=reshape(q_min,7,1); q_max=reshape(q_max,7,1);", ...
"", ...
"input_ok=numel(guard_parameters)>=3 && ...", ...
"    all(isfinite(qdot_raw(:))) && all(isfinite(q(:))) && ...", ...
"    all(isfinite(qdot_limit(:))) && all(qdot_limit>0.0) && ...", ...
"    all(isfinite(qddot_limit(:))) && all(qddot_limit>0.0) && ...", ...
"    all(isfinite(q_min(:))) && all(isfinite(q_max(:))) && ...", ...
"    all(q_max>q_min) && all(isfinite(guard_parameters(1:3)));", ...
"if ~input_ok", ...
"    filtered_velocity=zeros(7,1); previous_command=zeros(7,1); return;", ...
"end", ...
"", ...
"Ts=guard_parameters(1); filter_tau=guard_parameters(2);", ...
"soft_margin=guard_parameters(3);", ...
"parameter_ok=Ts>0.0 && filter_tau>=0.0 && soft_margin>0.0;", ...
"if ~parameter_ok", ...
"    filtered_velocity=zeros(7,1); previous_command=zeros(7,1); return;", ...
"end", ...
"", ...
"target_velocity=zeros(7,1);", ...
"% 使能或数据失效时把目标速度置零，但保留同一低通与加速度限制缓降。", ...
"if safe_valid && control_active && solver_valid", ...
"    target_velocity=qdot_raw;", ...
"end", ...
"", ...
"% 唯一一次命令低通滤波。tau=0 表示关闭。", ...
"alpha=Ts/(filter_tau+Ts);", ...
"filtered_velocity=filtered_velocity+alpha*(target_velocity-filtered_velocity);", ...
"", ...
"% 整体速度缩放：任一关节达到软件限值时，7 维方向同比例保留。", ...
"maximum_velocity_ratio=max(abs(filtered_velocity)./qdot_limit);", ...
"velocity_scale=1.0/max(1.0,maximum_velocity_ratio);", ...
"velocity_limited=filtered_velocity*velocity_scale;", ...
"", ...
"% 在建议矩形位置工作区的边缘做整体降速。", ...
"position_scale=1.0;", ...
"for joint_index=1:7", ...
"    if velocity_limited(joint_index)>0.0", ...
"        distance_to_limit=q_max(joint_index)-q(joint_index);", ...
"        local_scale=min(max(distance_to_limit/soft_margin,0.0),1.0);", ...
"        position_scale=min(position_scale,local_scale);", ...
"    elseif velocity_limited(joint_index)<0.0", ...
"        distance_to_limit=q(joint_index)-q_min(joint_index);", ...
"        local_scale=min(max(distance_to_limit/soft_margin,0.0),1.0);", ...
"        position_scale=min(position_scale,local_scale);", ...
"    end", ...
"end", ...
"velocity_limited=velocity_limited*position_scale;", ...
"", ...
"% 整体加速度缩放：限制本周期 7 维速度变化，保持变化方向。", ...
"delta_velocity=velocity_limited-previous_command;", ...
"maximum_acceleration_ratio=max(abs(delta_velocity)./(qddot_limit*Ts));", ...
"acceleration_scale=1.0/max(1.0,maximum_acceleration_ratio);", ...
"qdot_command=previous_command+delta_velocity*acceleration_scale;", ...
"", ...
"% 若已经到达软件位置边界，安全边界优先于平滑性，禁止继续向外。", ...
"emergency_position_scale=1.0;", ...
"for joint_index=1:7", ...
"    moving_outward=(q(joint_index)>=q_max(joint_index) && qdot_command(joint_index)>0.0) || ...", ...
"        (q(joint_index)<=q_min(joint_index) && qdot_command(joint_index)<0.0);", ...
"    if moving_outward, emergency_position_scale=0.0; end", ...
"end", ...
"qdot_command=qdot_command*emergency_position_scale;", ...
"position_scale=position_scale*emergency_position_scale;", ...
"", ...
"guard_valid=all(isfinite(qdot_command(:)));", ...
"if guard_valid", ...
"    previous_command=qdot_command;", ...
"else", ...
"    qdot_command=zeros(7,1); filtered_velocity=zeros(7,1);", ...
"    previous_command=zeros(7,1); velocity_scale=0.0;", ...
"    acceleration_scale=0.0; position_scale=0.0;", ...
"end", ...
"end" ...
], newline);

end


function codeText = publisherPackFunctionCode()

codeText = strjoin([ ...
"function [data,current_length,received_length] = fcn(qdot_command)", ...
"%#codegen", ...
"data=zeros(128,1);", ...
"data(1:7)=reshape(qdot_command,7,1);", ...
"current_length=uint32(7);", ...
"received_length=uint32(7);", ...
"end" ...
], newline);

end
